"""Unified provider interface for LLM completion.

Exports protocols, base classes, domain models, enums, errors,
driver implementations, and the provider registry.
"""

from .base import BaseCompletionProvider
from .capabilities import ModelCapabilities
from .drivers import LiteLLMDriver
from .enums import FinishReason, MessageRole, StreamEventType
from .errors import (
    AuthenticationError,
    ContentFilterError,
    DriverAlreadyRegisteredError,
    DriverFactoryNotFoundError,
    DriverNotRegisteredError,
    InvalidRequestError,
    ModelNotFoundError,
    ProviderConnectionError,
    ProviderError,
    ProviderInternalError,
    ProviderTimeoutError,
    RateLimitError,
)
from .models import (
    ChatMessage,
    CompletionConfig,
    CompletionResponse,
    StreamChunk,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    ToolResult,
)
from .protocol import CompletionProvider
from .registry import ProviderRegistry
from .resilience import (
    RateLimiter,
    RateLimiterConfig,
    RetryConfig,
    RetryExhaustedError,
    RetryHandler,
)
from .routing import (
    STRATEGY_MAP,
    STRATEGY_NAME_CHEAPEST,
    STRATEGY_NAME_COST_AWARE,
    STRATEGY_NAME_MANUAL,
    STRATEGY_NAME_ROLE_BASED,
    STRATEGY_NAME_SMART,
    CostAwareStrategy,
    ManualStrategy,
    ModelResolutionError,
    ModelResolver,
    ModelRouter,
    NoAvailableModelError,
    ResolvedModel,
    RoleBasedStrategy,
    RoutingDecision,
    RoutingError,
    RoutingRequest,
    RoutingStrategy,
    SmartStrategy,
    UnknownStrategyError,
)

__all__ = [
    "STRATEGY_MAP",
    "STRATEGY_NAME_CHEAPEST",
    "STRATEGY_NAME_COST_AWARE",
    "STRATEGY_NAME_MANUAL",
    "STRATEGY_NAME_ROLE_BASED",
    "STRATEGY_NAME_SMART",
    "AuthenticationError",
    "BaseCompletionProvider",
    "ChatMessage",
    "CompletionConfig",
    "CompletionProvider",
    "CompletionResponse",
    "ContentFilterError",
    "CostAwareStrategy",
    "DriverAlreadyRegisteredError",
    "DriverFactoryNotFoundError",
    "DriverNotRegisteredError",
    "FinishReason",
    "InvalidRequestError",
    "LiteLLMDriver",
    "ManualStrategy",
    "MessageRole",
    "ModelCapabilities",
    "ModelNotFoundError",
    "ModelResolutionError",
    "ModelResolver",
    "ModelRouter",
    "NoAvailableModelError",
    "ProviderConnectionError",
    "ProviderError",
    "ProviderInternalError",
    "ProviderRegistry",
    "ProviderTimeoutError",
    "RateLimitError",
    "RateLimiter",
    "RateLimiterConfig",
    "ResolvedModel",
    "RetryConfig",
    "RetryExhaustedError",
    "RetryHandler",
    "RoleBasedStrategy",
    "RoutingDecision",
    "RoutingError",
    "RoutingRequest",
    "RoutingStrategy",
    "SmartStrategy",
    "StreamChunk",
    "StreamEventType",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "UnknownStrategyError",
]
