"""Template event constants."""

from typing import Final

TEMPLATE_LOAD_START: Final[str] = "template.load.start"
TEMPLATE_LOAD_SUCCESS: Final[str] = "template.load.success"
TEMPLATE_LOAD_ERROR: Final[str] = "template.load.error"
TEMPLATE_LIST_SKIP_INVALID: Final[str] = "template.list.skip_invalid"
TEMPLATE_BUILTIN_DEFECT: Final[str] = "template.builtin.defect"
TEMPLATE_RENDER_START: Final[str] = "template.render.start"
TEMPLATE_RENDER_SUCCESS: Final[str] = "template.render.success"
TEMPLATE_RENDER_VARIABLE_ERROR: Final[str] = "template.render.variable_error"
TEMPLATE_RENDER_JINJA2_ERROR: Final[str] = "template.render.jinja2_error"
TEMPLATE_RENDER_YAML_ERROR: Final[str] = "template.render.yaml_error"
TEMPLATE_RENDER_VALIDATION_ERROR: Final[str] = "template.render.validation_error"
TEMPLATE_PERSONALITY_PRESET_UNKNOWN: Final[str] = "template.personality_preset.unknown"
TEMPLATE_PASS1_FLOAT_FALLBACK: Final[str] = "template.pass1.float_fallback"
TEMPLATE_INHERIT_RESOLVE_START: Final[str] = "template.inherit.resolve_start"
TEMPLATE_INHERIT_RESOLVE_SUCCESS: Final[str] = "template.inherit.resolve_success"
TEMPLATE_INHERIT_CIRCULAR: Final[str] = "template.inherit.circular"
TEMPLATE_INHERIT_DEPTH_EXCEEDED: Final[str] = "template.inherit.depth_exceeded"
TEMPLATE_INHERIT_MERGE: Final[str] = "template.inherit.merge"
TEMPLATE_INHERIT_MERGE_ERROR: Final[str] = "template.inherit.merge_error"
TEMPLATE_RENDER_TYPE_ERROR: Final[str] = "template.render.type_error"
TEMPLATE_LOAD_NOT_FOUND: Final[str] = "template.load.not_found"
TEMPLATE_LOAD_READ_ERROR: Final[str] = "template.load.read_error"
TEMPLATE_LOAD_PARSE_ERROR: Final[str] = "template.load.parse_error"
TEMPLATE_LOAD_STRUCTURE_ERROR: Final[str] = "template.load.structure_error"
TEMPLATE_LOAD_INVALID_NAME: Final[str] = "template.load.invalid_name"
TEMPLATE_SCHEMA_VALIDATION_ERROR: Final[str] = "template.schema.validation_error"
