"""Core domain models for the SynthOrg framework."""

from ai_company.core.agent import (
    AgentIdentity,
    MemoryConfig,
    ModelConfig,
    PersonalityConfig,
    SkillSet,
    ToolPermissions,
)
from ai_company.core.approval import ApprovalItem
from ai_company.core.artifact import Artifact, ExpectedArtifact
from ai_company.core.company import (
    ApprovalChain,
    Company,
    CompanyConfig,
    Department,
    DepartmentPolicies,
    EscalationPath,
    HRRegistry,
    ReportingLine,
    ReviewRequirements,
    Team,
    WorkflowHandoff,
)
from ai_company.core.enums import (
    ActionType,
    AgentStatus,
    ApprovalRiskLevel,
    ApprovalStatus,
    ArtifactType,
    CollaborationPreference,
    CommunicationVerbosity,
    CompanyType,
    Complexity,
    ConflictApproach,
    ConsolidationInterval,
    CoordinationTopology,
    CostTier,
    CreativityLevel,
    DecisionMakingStyle,
    DepartmentName,
    MemoryCategory,
    MemoryLevel,
    Priority,
    ProficiencyLevel,
    ProjectStatus,
    RiskTolerance,
    SeniorityLevel,
    SkillCategory,
    TaskStatus,
    TaskStructure,
    TaskType,
    ToolAccessLevel,
    ToolCategory,
)
from ai_company.core.project import Project
from ai_company.core.role import (
    Authority,
    CustomRole,
    Role,
    SeniorityInfo,
    Skill,
)
from ai_company.core.role_catalog import (
    BUILTIN_ROLES,
    SENIORITY_INFO,
    get_builtin_role,
    get_seniority_info,
)
from ai_company.core.task import AcceptanceCriterion, Task
from ai_company.core.task_transitions import VALID_TRANSITIONS, validate_transition
from ai_company.core.types import NotBlankStr, validate_unique_strings

__all__ = [
    "BUILTIN_ROLES",
    "SENIORITY_INFO",
    "VALID_TRANSITIONS",
    "AcceptanceCriterion",
    "ActionType",
    "AgentIdentity",
    "AgentStatus",
    "ApprovalChain",
    "ApprovalItem",
    "ApprovalRiskLevel",
    "ApprovalStatus",
    "Artifact",
    "ArtifactType",
    "Authority",
    "CollaborationPreference",
    "CommunicationVerbosity",
    "Company",
    "CompanyConfig",
    "CompanyType",
    "Complexity",
    "ConflictApproach",
    "ConsolidationInterval",
    "CoordinationTopology",
    "CostTier",
    "CreativityLevel",
    "CustomRole",
    "DecisionMakingStyle",
    "Department",
    "DepartmentName",
    "DepartmentPolicies",
    "EscalationPath",
    "ExpectedArtifact",
    "HRRegistry",
    "MemoryCategory",
    "MemoryConfig",
    "MemoryLevel",
    "ModelConfig",
    "NotBlankStr",
    "PersonalityConfig",
    "Priority",
    "ProficiencyLevel",
    "Project",
    "ProjectStatus",
    "ReportingLine",
    "ReviewRequirements",
    "RiskTolerance",
    "Role",
    "SeniorityInfo",
    "SeniorityLevel",
    "Skill",
    "SkillCategory",
    "SkillSet",
    "Task",
    "TaskStatus",
    "TaskStructure",
    "TaskType",
    "Team",
    "ToolAccessLevel",
    "ToolCategory",
    "ToolPermissions",
    "WorkflowHandoff",
    "get_builtin_role",
    "get_seniority_info",
    "validate_transition",
    "validate_unique_strings",
]
