"""Agent execution engine.

Re-exports the public API for the agent orchestrator, task engine,
run results, system prompt construction, runtime execution state,
execution loops, and engine errors.
"""

from ai_company.engine.agent_engine import AgentEngine
from ai_company.engine.approval_gate import ApprovalGate
from ai_company.engine.approval_gate_models import EscalationInfo, ResumePayload
from ai_company.engine.assignment import (
    STRATEGY_MAP,
    STRATEGY_NAME_AUCTION,
    STRATEGY_NAME_COST_OPTIMIZED,
    STRATEGY_NAME_HIERARCHICAL,
    STRATEGY_NAME_LOAD_BALANCED,
    STRATEGY_NAME_MANUAL,
    STRATEGY_NAME_ROLE_BASED,
    AgentWorkload,
    AssignmentCandidate,
    AssignmentRequest,
    AssignmentResult,
    AuctionAssignmentStrategy,
    CostOptimizedAssignmentStrategy,
    HierarchicalAssignmentStrategy,
    LoadBalancedAssignmentStrategy,
    ManualAssignmentStrategy,
    RoleBasedAssignmentStrategy,
    TaskAssignmentService,
    TaskAssignmentStrategy,
    build_strategy_map,
)
from ai_company.engine.checkpoint import (
    Checkpoint,
    CheckpointCallback,
    CheckpointConfig,
    CheckpointRecoveryStrategy,
    Heartbeat,
    make_checkpoint_callback,
)
from ai_company.engine.classification import (
    ClassificationResult,
    ErrorFinding,
    ErrorSeverity,
    classify_execution_errors,
)
from ai_company.engine.context import (
    DEFAULT_MAX_TURNS,
    AgentContext,
    AgentContextSnapshot,
)
from ai_company.engine.coordination import (
    CentralizedDispatcher,
    ContextDependentDispatcher,
    CoordinationConfig,
    CoordinationContext,
    CoordinationPhaseResult,
    CoordinationResult,
    CoordinationWave,
    DecentralizedDispatcher,
    DispatchResult,
    MultiAgentCoordinator,
    SasDispatcher,
    TopologyDispatcher,
    build_execution_waves,
    select_dispatcher,
)
from ai_company.engine.decomposition import (
    DecompositionContext,
    DecompositionPlan,
    DecompositionResult,
    DecompositionService,
    DecompositionStrategy,
    DependencyGraph,
    LlmDecompositionConfig,
    LlmDecompositionStrategy,
    ManualDecompositionStrategy,
    StatusRollup,
    SubtaskDefinition,
    SubtaskStatusRollup,
    TaskStructureClassifier,
)
from ai_company.engine.errors import (
    CoordinationError,
    CoordinationPhaseError,
    DecompositionCycleError,
    DecompositionDepthError,
    DecompositionError,
    EngineError,
    ExecutionStateError,
    LoopExecutionError,
    MaxTurnsExceededError,
    NoEligibleAgentError,
    ParallelExecutionError,
    PromptBuildError,
    ResourceConflictError,
    TaskAssignmentError,
    TaskEngineError,
    TaskEngineNotRunningError,
    TaskEngineQueueFullError,
    TaskInternalError,
    TaskMutationError,
    TaskNotFoundError,
    TaskRoutingError,
    TaskVersionConflictError,
    WorkspaceCleanupError,
    WorkspaceError,
    WorkspaceLimitError,
    WorkspaceMergeError,
    WorkspaceSetupError,
)
from ai_company.engine.loop_protocol import (
    BudgetChecker,
    ExecutionLoop,
    ExecutionResult,
    ShutdownChecker,
    TerminationReason,
    TurnRecord,
)
from ai_company.engine.metrics import TaskCompletionMetrics
from ai_company.engine.parallel import ParallelExecutor, ProgressCallback
from ai_company.engine.parallel_models import (
    AgentAssignment,
    AgentOutcome,
    ParallelExecutionGroup,
    ParallelExecutionResult,
    ParallelProgress,
)
from ai_company.engine.plan_execute_loop import PlanExecuteLoop
from ai_company.engine.plan_models import (
    ExecutionPlan,
    PlanExecuteConfig,
    PlanStep,
    StepStatus,
)
from ai_company.engine.prompt import (
    DefaultTokenEstimator,
    PromptTokenEstimator,
    SystemPrompt,
    build_system_prompt,
)
from ai_company.engine.react_loop import ReactLoop
from ai_company.engine.recovery import (
    FailAndReassignStrategy,
    RecoveryResult,
    RecoveryStrategy,
)
from ai_company.engine.resource_lock import InMemoryResourceLock, ResourceLock
from ai_company.engine.routing import (
    AgentTaskScorer,
    AutoTopologyConfig,
    RoutingCandidate,
    RoutingDecision,
    RoutingResult,
    TaskRoutingService,
    TopologySelector,
)
from ai_company.engine.run_result import AgentRunResult
from ai_company.engine.shutdown import (
    CleanupCallback,
    CooperativeTimeoutStrategy,
    ShutdownManager,
    ShutdownResult,
    ShutdownStrategy,
)
from ai_company.engine.task_engine import TaskEngine
from ai_company.engine.task_engine_config import TaskEngineConfig
from ai_company.engine.task_engine_models import (
    CancelTaskMutation,
    CreateTaskData,
    CreateTaskMutation,
    DeleteTaskMutation,
    TaskMutation,
    TaskMutationResult,
    TaskStateChanged,
    TransitionTaskMutation,
    UpdateTaskMutation,
)
from ai_company.engine.task_execution import StatusTransition, TaskExecution
from ai_company.engine.workspace import (
    MergeConflict,
    MergeOrchestrator,
    MergeResult,
    PlannerWorktreesConfig,
    PlannerWorktreeStrategy,
    Workspace,
    WorkspaceGroupResult,
    WorkspaceIsolationConfig,
    WorkspaceIsolationService,
    WorkspaceIsolationStrategy,
    WorkspaceRequest,
)
from ai_company.providers.models import ZERO_TOKEN_USAGE, add_token_usage

__all__ = [
    "DEFAULT_MAX_TURNS",
    "STRATEGY_MAP",
    "STRATEGY_NAME_AUCTION",
    "STRATEGY_NAME_COST_OPTIMIZED",
    "STRATEGY_NAME_HIERARCHICAL",
    "STRATEGY_NAME_LOAD_BALANCED",
    "STRATEGY_NAME_MANUAL",
    "STRATEGY_NAME_ROLE_BASED",
    "ZERO_TOKEN_USAGE",
    "AgentAssignment",
    "AgentContext",
    "AgentContextSnapshot",
    "AgentEngine",
    "AgentOutcome",
    "AgentRunResult",
    "AgentTaskScorer",
    "AgentWorkload",
    "ApprovalGate",
    "AssignmentCandidate",
    "AssignmentRequest",
    "AssignmentResult",
    "AuctionAssignmentStrategy",
    "AutoTopologyConfig",
    "BudgetChecker",
    "CancelTaskMutation",
    "CentralizedDispatcher",
    "Checkpoint",
    "CheckpointCallback",
    "CheckpointConfig",
    "CheckpointRecoveryStrategy",
    "ClassificationResult",
    "CleanupCallback",
    "ContextDependentDispatcher",
    "CooperativeTimeoutStrategy",
    "CoordinationConfig",
    "CoordinationContext",
    "CoordinationError",
    "CoordinationPhaseError",
    "CoordinationPhaseResult",
    "CoordinationResult",
    "CoordinationWave",
    "CostOptimizedAssignmentStrategy",
    "CreateTaskData",
    "CreateTaskMutation",
    "DecentralizedDispatcher",
    "DecompositionContext",
    "DecompositionCycleError",
    "DecompositionDepthError",
    "DecompositionError",
    "DecompositionPlan",
    "DecompositionResult",
    "DecompositionService",
    "DecompositionStrategy",
    "DefaultTokenEstimator",
    "DeleteTaskMutation",
    "DependencyGraph",
    "DispatchResult",
    "EngineError",
    "ErrorFinding",
    "ErrorSeverity",
    "EscalationInfo",
    "ExecutionLoop",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionStateError",
    "FailAndReassignStrategy",
    "Heartbeat",
    "HierarchicalAssignmentStrategy",
    "InMemoryResourceLock",
    "LlmDecompositionConfig",
    "LlmDecompositionStrategy",
    "LoadBalancedAssignmentStrategy",
    "LoopExecutionError",
    "ManualAssignmentStrategy",
    "ManualDecompositionStrategy",
    "MaxTurnsExceededError",
    "MergeConflict",
    "MergeOrchestrator",
    "MergeResult",
    "MultiAgentCoordinator",
    "NoEligibleAgentError",
    "ParallelExecutionError",
    "ParallelExecutionGroup",
    "ParallelExecutionResult",
    "ParallelExecutor",
    "ParallelProgress",
    "PlanExecuteConfig",
    "PlanExecuteLoop",
    "PlanStep",
    "PlannerWorktreeStrategy",
    "PlannerWorktreesConfig",
    "ProgressCallback",
    "PromptBuildError",
    "PromptTokenEstimator",
    "ReactLoop",
    "RecoveryResult",
    "RecoveryStrategy",
    "ResourceConflictError",
    "ResourceLock",
    "ResumePayload",
    "RoleBasedAssignmentStrategy",
    "RoutingCandidate",
    "RoutingDecision",
    "RoutingResult",
    "SasDispatcher",
    "ShutdownChecker",
    "ShutdownManager",
    "ShutdownResult",
    "ShutdownStrategy",
    "StatusRollup",
    "StatusTransition",
    "StepStatus",
    "SubtaskDefinition",
    "SubtaskStatusRollup",
    "SystemPrompt",
    "TaskAssignmentError",
    "TaskAssignmentService",
    "TaskAssignmentStrategy",
    "TaskCompletionMetrics",
    "TaskEngine",
    "TaskEngineConfig",
    "TaskEngineError",
    "TaskEngineNotRunningError",
    "TaskEngineQueueFullError",
    "TaskExecution",
    "TaskInternalError",
    "TaskMutation",
    "TaskMutationError",
    "TaskMutationResult",
    "TaskNotFoundError",
    "TaskRoutingError",
    "TaskRoutingService",
    "TaskStateChanged",
    "TaskStructureClassifier",
    "TaskVersionConflictError",
    "TerminationReason",
    "TopologyDispatcher",
    "TopologySelector",
    "TransitionTaskMutation",
    "TurnRecord",
    "UpdateTaskMutation",
    "Workspace",
    "WorkspaceCleanupError",
    "WorkspaceError",
    "WorkspaceGroupResult",
    "WorkspaceIsolationConfig",
    "WorkspaceIsolationService",
    "WorkspaceIsolationStrategy",
    "WorkspaceLimitError",
    "WorkspaceMergeError",
    "WorkspaceRequest",
    "WorkspaceSetupError",
    "add_token_usage",
    "build_execution_waves",
    "build_strategy_map",
    "build_system_prompt",
    "classify_execution_errors",
    "make_checkpoint_callback",
    "select_dispatcher",
]
