package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/Aureliolo/synthorg/cli/internal/compose"
	"github.com/Aureliolo/synthorg/cli/internal/config"
	"github.com/Aureliolo/synthorg/cli/internal/images"
	"github.com/spf13/cobra"
)

// refreshCompose regenerates compose.yml from the current embedded template.
// If the regenerated compose differs from what is on disk, it shows the diff
// and asks the user to approve. When force is true (recovery mode), a missing
// compose.yml is generated from the template without prompting.
// Returns true if compose is up to date or changes were applied; false if
// the user declined.
func refreshCompose(cmd *cobra.Command, state config.State, force bool) (bool, error) {
	out := cmd.OutOrStdout()

	safeDir, err := safeStateDir(state)
	if err != nil {
		return false, err
	}

	composePath := filepath.Join(safeDir, "compose.yml")
	existing, fresh, err := loadAndGenerate(composePath, state)
	if err != nil {
		return false, err
	}
	if existing == nil {
		if !force {
			return true, nil // no compose.yml on disk -- nothing to refresh
		}
		return recoverMissingCompose(out, composePath, state, safeDir)
	}

	if bytes.Equal(existing, fresh) {
		_, _ = fmt.Fprintln(out, "Compose configuration is up to date.")
		return true, nil
	}

	// Auto-apply when only the version comment and/or image references
	// changed -- these are expected during an update and don't need
	// user confirmation (template structure is unchanged).
	if isUpdateBoilerplateOnly(existing, fresh) {
		if err := atomicWriteFile(composePath, fresh, safeDir); err != nil {
			return false, fmt.Errorf("writing updated compose: %w", err)
		}
		_, _ = fmt.Fprintln(out, "Compose configuration is up to date.")
		return true, nil
	}

	return applyComposeDiff(cmd, composePath, existing, fresh, safeDir, state.AutoApplyCompose)
}

// recoverMissingCompose generates compose.yml from the template during
// recovery mode when the file is absent.
func recoverMissingCompose(out io.Writer, composePath string, state config.State, safeDir string) (bool, error) {
	params := compose.ParamsFromState(state)
	params.DigestPins = state.VerifiedDigests
	generated, genErr := compose.Generate(params)
	if genErr != nil {
		return false, fmt.Errorf("generating compose.yml during recovery: %w", genErr)
	}
	if wErr := atomicWriteFile(composePath, generated, safeDir); wErr != nil {
		return false, fmt.Errorf("writing compose.yml during recovery: %w", wErr)
	}
	_, _ = fmt.Fprintln(out, "Generated compose.yml from template.")
	return true, nil
}

// isUpdateBoilerplateOnly returns true if the only differences between
// existing and fresh are the version comment (line 1) and/or image
// references. These change on every update and don't need user approval.
func isUpdateBoilerplateOnly(existing, fresh []byte) bool {
	oldLines := strings.Split(string(existing), "\n")
	newLines := strings.Split(string(fresh), "\n")
	if len(oldLines) != len(newLines) {
		return false
	}
	for i := range oldLines {
		if oldLines[i] == newLines[i] {
			continue
		}
		// Allow version comment difference (line 1).
		if i == 0 && strings.HasPrefix(oldLines[i], "# Generated by SynthOrg CLI") &&
			strings.HasPrefix(newLines[i], "# Generated by SynthOrg CLI") {
			continue
		}
		// Allow image reference differences for the same service.
		oldSub := imageLinePattern.FindStringSubmatch(oldLines[i])
		newSub := imageLinePattern.FindStringSubmatch(newLines[i])
		if len(oldSub) >= 3 && len(newSub) >= 3 && oldSub[2] == newSub[2] {
			continue
		}
		return false
	}
	return true
}

// loadAndGenerate reads the existing compose and generates a fresh one from
// the template. Returns (nil, nil, nil) if no compose.yml exists on disk.
func loadAndGenerate(composePath string, state config.State) ([]byte, []byte, error) {
	existing, err := os.ReadFile(composePath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, nil, nil
		}
		return nil, nil, fmt.Errorf("reading existing compose: %w", err)
	}

	params := compose.ParamsFromState(state)
	params.DigestPins = state.VerifiedDigests
	fresh, err := compose.Generate(params)
	if err != nil {
		return nil, nil, fmt.Errorf("generating compose from template: %w", err)
	}
	return existing, fresh, nil
}

// applyComposeDiff shows the diff between existing and fresh compose,
// asks the user to approve, and writes the fresh compose if approved.
// Returns true if applied, false if declined.
func applyComposeDiff(cmd *cobra.Command, composePath string, existing, fresh []byte, safeDir string, autoApply bool) (bool, error) {
	out := cmd.OutOrStdout()

	diff := lineDiff(string(existing), string(fresh))
	_, _ = fmt.Fprintln(out, "Compose template has changed:")
	_, _ = fmt.Fprintln(out, diff)

	ok, err := confirmUpdate(cmd.Context(), "Apply compose configuration changes?", autoApply)
	if err != nil {
		return false, err
	}
	if !ok {
		_, _ = fmt.Fprintln(out, "Compose changes skipped.")
		return false, nil
	}

	if err := atomicWriteFile(composePath, fresh, safeDir); err != nil {
		return false, fmt.Errorf("writing updated compose: %w", err)
	}
	_, _ = fmt.Fprintln(out, "Compose configuration updated.")
	return true, nil
}

// secretKeyPattern matches YAML lines containing known sensitive keys.
// Used by lineDiff to redact sensitive values before displaying.
// Covers common secret naming conventions to prevent leaking credentials
// in terminal scrollback or CI logs when the compose template changes.
var secretKeyPattern = regexp.MustCompile(
	`(?i)^\s*\w*(SECRET|PASSWORD|TOKEN|API_KEY|CREDENTIALS|ENCRYPTION_KEY|SETTINGS_KEY|PRIVATE_KEY|CERT)\w*\s*:`,
)

// lineDiff produces a bag-based diff showing added (+) and removed (-) lines
// between two strings. Lines containing secret keys are redacted.
//
// Note: this uses multiset membership, not positional diffing. Reordered
// lines are not reported as changes. This is acceptable for compose files
// where the user approves structural additions/removals, not reorderings.
func lineDiff(oldText, updated string) string {
	oldLines := strings.Split(oldText, "\n")
	newLines := strings.Split(updated, "\n")

	newSet := make(map[string]int, len(newLines))
	for _, l := range newLines {
		newSet[l]++
	}

	oldSet := make(map[string]int, len(oldLines))
	for _, l := range oldLines {
		oldSet[l]++
	}

	var b strings.Builder
	for _, l := range oldLines {
		if newSet[l] > 0 {
			newSet[l]--
			continue
		}
		b.WriteString("  - ")
		b.WriteString(redactSecret(l))
		b.WriteByte('\n')
	}
	for _, l := range newLines {
		if oldSet[l] > 0 {
			oldSet[l]--
			continue
		}
		b.WriteString("  + ")
		b.WriteString(redactSecret(l))
		b.WriteByte('\n')
	}
	return b.String()
}

// redactSecret replaces secret values with [REDACTED] in diff output.
// Uses the regex submatch end position to find the colon reliably,
// rather than scanning from the start of the line.
func redactSecret(line string) string {
	loc := secretKeyPattern.FindStringIndex(line)
	if loc != nil {
		// loc[1] is past the trailing ":", so the key + colon is line[:loc[1]].
		return line[:loc[1]] + " [REDACTED]"
	}
	return line
}

// writeOrPatchCompose either regenerates compose from the template or
// patches only image references in the existing file.
func writeOrPatchCompose(state config.State, digestPins map[string]string, safeDir string, preserveCompose bool) error {
	if !preserveCompose {
		return writeDigestPinnedCompose(state, digestPins, safeDir)
	}
	return patchComposeImageRefs(state.ImageTag, digestPins, state.Sandbox, safeDir)
}

// imageLinePattern matches Docker image references in compose YAML.
// Handles both digest-pinned (repo@sha256:...) and tag-based (repo:tag).
// The pattern anchors after the service name with an optional [:@] suffix
// to avoid matching extended repo names (e.g. synthorg-backend-fips).
var imageLinePattern = regexp.MustCompile(
	`(\s+image:\s+)ghcr\.io/aureliolo/synthorg-(backend|web|sandbox)(?:[:@]\S+)?`,
)

// patchComposeImageRefs updates only the image references in an existing
// compose.yml without regenerating from the template. This preserves the
// user's compose configuration while allowing image updates.
//
// Returns an error if no image references were found or if not all expected
// services (backend, web, and optionally sandbox) were patched -- this
// prevents config.Save from advancing state when compose is unpatched.
func patchComposeImageRefs(tag string, digestPins map[string]string, sandboxEnabled bool, safeDir string) error {
	composePath := filepath.Join(safeDir, "compose.yml")
	existing, err := os.ReadFile(composePath)
	if err != nil {
		return fmt.Errorf("reading compose for image patching: %w", err)
	}

	replaced := make(map[string]bool)
	patched := imageLinePattern.ReplaceAllStringFunc(string(existing), func(match string) string {
		sub := imageLinePattern.FindStringSubmatch(match)
		if len(sub) < 3 {
			return match
		}
		prefix := sub[1] // e.g. "    image: "
		name := sub[2]   // e.g. "backend"
		repo := images.RepoPrefix + name
		replaced[name] = true

		if d, ok := digestPins[name]; ok && d != "" {
			return prefix + repo + "@" + d
		}
		return prefix + repo + ":" + tag
	})

	if len(replaced) == 0 {
		return fmt.Errorf("no synthorg image references found in %s -- compose may be manually edited; run 'synthorg init' to regenerate", composePath)
	}

	// Backend and web are always required; sandbox only when enabled.
	required := []string{"backend", "web"}
	if sandboxEnabled {
		required = append(required, "sandbox")
	}
	for _, svc := range required {
		if !replaced[svc] {
			return fmt.Errorf("image reference for %q not found in %s -- compose may be manually edited; run 'synthorg init' to regenerate", svc, composePath)
		}
	}

	return atomicWriteFile(composePath, []byte(patched), safeDir)
}
