"""Client simulation domain models.

Defines the data structures for client profiles, task requirements,
feedback, requests, and simulation metrics. All models are frozen
Pydantic models following project conventions.
"""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, Self
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, computed_field, model_validator

from synthorg.core.enums import Complexity, Priority, TaskType
from synthorg.core.types import NotBlankStr  # noqa: TC001


class RequestStatus(StrEnum):
    """Lifecycle status of a client request through the intake pipeline.

    Independent from ``TaskStatus`` -- tracks the intake process
    before a task is created in the task engine.

    Transitions::

        SUBMITTED -> TRIAGING -> SCOPING -> APPROVED -> TASK_CREATED
        Any non-terminal state -> CANCELLED
    """

    SUBMITTED = "submitted"
    TRIAGING = "triaging"
    SCOPING = "scoping"
    APPROVED = "approved"
    TASK_CREATED = "task_created"
    CANCELLED = "cancelled"


VALID_REQUEST_TRANSITIONS: dict[RequestStatus, frozenset[RequestStatus]] = {
    RequestStatus.SUBMITTED: frozenset(
        {RequestStatus.TRIAGING, RequestStatus.CANCELLED}
    ),
    RequestStatus.TRIAGING: frozenset({RequestStatus.SCOPING, RequestStatus.CANCELLED}),
    RequestStatus.SCOPING: frozenset({RequestStatus.APPROVED, RequestStatus.CANCELLED}),
    RequestStatus.APPROVED: frozenset(
        {RequestStatus.TASK_CREATED, RequestStatus.CANCELLED}
    ),
    RequestStatus.TASK_CREATED: frozenset(),
    RequestStatus.CANCELLED: frozenset(),
}

_missing_request = set(RequestStatus) - set(VALID_REQUEST_TRANSITIONS)
if _missing_request:
    _msg = (
        "Missing request transition entries for: "
        f"{sorted(s.value for s in _missing_request)}"
    )
    raise ValueError(_msg)


def validate_request_transition(
    current: RequestStatus,
    target: RequestStatus,
) -> None:
    """Validate that a request status transition is allowed.

    Args:
        current: The current request status.
        target: The desired target status.

    Raises:
        ValueError: If the transition is not valid.
    """
    allowed = VALID_REQUEST_TRANSITIONS.get(current)
    if allowed is None:
        msg = f"RequestStatus {current.value!r} has no transition entry."
        raise ValueError(msg)
    if target not in allowed:
        msg = (
            f"Invalid request transition: {current.value!r} -> "
            f"{target.value!r}. Allowed: "
            f"{sorted(s.value for s in allowed)}"
        )
        raise ValueError(msg)


class ClientProfile(BaseModel):
    """Profile of a client participating in simulation.

    Attributes:
        client_id: Unique client identifier.
        name: Human-readable client name.
        persona: Description of the client's persona and behavior.
        expertise_domains: Domains the client is knowledgeable about.
        strictness_level: How strict the client is during reviews
            (0.0 = lenient, 1.0 = very strict).
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    client_id: NotBlankStr = Field(description="Unique client identifier")
    name: NotBlankStr = Field(description="Human-readable client name")
    persona: NotBlankStr = Field(
        description="Description of the client's persona",
    )
    expertise_domains: tuple[NotBlankStr, ...] = Field(
        default=(),
        description="Domains the client is knowledgeable about",
    )
    strictness_level: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Review strictness (0.0=lenient, 1.0=strict)",
    )


class TaskRequirement(BaseModel):
    """A task requirement generated by a client or generator.

    Attributes:
        title: Short requirement title.
        description: Detailed requirement description.
        task_type: Classification of the work type.
        priority: Urgency and importance level.
        estimated_complexity: Estimated task complexity.
        acceptance_criteria: Criteria for task acceptance.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    title: NotBlankStr = Field(description="Short requirement title")
    description: NotBlankStr = Field(
        description="Detailed requirement description",
    )
    task_type: TaskType = Field(
        default=TaskType.DEVELOPMENT,
        description="Classification of the work type",
    )
    priority: Priority = Field(
        default=Priority.MEDIUM,
        description="Urgency and importance level",
    )
    estimated_complexity: Complexity = Field(
        default=Complexity.MEDIUM,
        description="Estimated task complexity",
    )
    acceptance_criteria: tuple[NotBlankStr, ...] = Field(
        default=(),
        description="Criteria for task acceptance",
    )


class GenerationContext(BaseModel):
    """Context provided to requirement generators.

    Attributes:
        project_id: Project to generate requirements for.
        domain: Domain area for requirement generation.
        complexity_range: Allowed complexity levels.
        count: Number of requirements to generate.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    project_id: NotBlankStr = Field(
        description="Project to generate requirements for",
    )
    domain: NotBlankStr = Field(
        description="Domain area for requirement generation",
    )
    complexity_range: tuple[Complexity, ...] = Field(
        default=(Complexity.SIMPLE, Complexity.MEDIUM, Complexity.COMPLEX),
        description="Allowed complexity levels",
    )
    count: int = Field(
        default=1,
        gt=0,
        description="Number of requirements to generate",
    )

    @model_validator(mode="after")
    def _validate_complexity_range(self) -> Self:
        """Ensure at least one complexity level is included."""
        if not self.complexity_range:
            msg = "complexity_range must not be empty"
            raise ValueError(msg)
        return self


class ReviewContext(BaseModel):
    """Context provided to feedback strategies for deliverable review.

    Attributes:
        task_id: ID of the task being reviewed.
        task_title: Title of the task being reviewed.
        acceptance_criteria: Original acceptance criteria.
        deliverable_summary: Summary of the deliverable output.
        prior_feedback: Previous feedback on this task (for rework).
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    task_id: NotBlankStr = Field(
        description="ID of the task being reviewed",
    )
    task_title: NotBlankStr = Field(
        description="Title of the task being reviewed",
    )
    acceptance_criteria: tuple[NotBlankStr, ...] = Field(
        default=(),
        description="Original acceptance criteria",
    )
    deliverable_summary: NotBlankStr = Field(
        description="Summary of the deliverable output",
    )
    prior_feedback: tuple[NotBlankStr, ...] = Field(
        default=(),
        description="Previous feedback on this task",
    )


class ClientFeedback(BaseModel):
    """Feedback from a client on a task deliverable.

    Attributes:
        feedback_id: Unique feedback identifier.
        task_id: ID of the reviewed task.
        client_id: ID of the reviewing client.
        accepted: Whether the deliverable was accepted.
        reason: Explanation for the decision.
        scores: Optional per-dimension scores.
        unmet_criteria: Criteria that were not satisfied.
        created_at: Timestamp of feedback creation.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    feedback_id: NotBlankStr = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique feedback identifier",
    )
    task_id: NotBlankStr = Field(
        description="ID of the reviewed task",
    )
    client_id: NotBlankStr = Field(
        description="ID of the reviewing client",
    )
    accepted: bool = Field(description="Whether the deliverable was accepted")
    reason: NotBlankStr | None = Field(
        default=None,
        description="Explanation for the decision",
    )
    scores: dict[str, float] | None = Field(
        default=None,
        description="Optional per-dimension scores (0.0-1.0)",
    )
    unmet_criteria: tuple[NotBlankStr, ...] = Field(
        default=(),
        description="Criteria that were not satisfied",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Timestamp of feedback creation",
    )

    @model_validator(mode="after")
    def _validate_rejection_has_reason(self) -> Self:
        """Rejected feedback must include a reason."""
        if not self.accepted and self.reason is None:
            msg = "reason is required when accepted is False"
            raise ValueError(msg)
        return self

    @model_validator(mode="after")
    def _validate_scores_range(self) -> Self:
        """Ensure all scores are in [0.0, 1.0] range."""
        if self.scores is not None:
            for key, value in self.scores.items():
                if not (0.0 <= value <= 1.0):
                    msg = f"scores[{key!r}] must be in [0.0, 1.0], got {value}"
                    raise ValueError(msg)
        return self


class ClientRequest(BaseModel):
    """A client's request submitted to the intake pipeline.

    Attributes:
        request_id: Unique request identifier.
        client_id: ID of the submitting client.
        requirement: The task requirement being requested.
        status: Current intake pipeline status.
        created_at: Timestamp of request creation.
        metadata: Additional request metadata.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    request_id: NotBlankStr = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique request identifier",
    )
    client_id: NotBlankStr = Field(
        description="ID of the submitting client",
    )
    requirement: TaskRequirement = Field(
        description="The task requirement being requested",
    )
    status: RequestStatus = Field(
        default=RequestStatus.SUBMITTED,
        description="Current intake pipeline status",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="Timestamp of request creation",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional request metadata",
    )

    def with_status(
        self,
        target: RequestStatus,
        **overrides: Any,
    ) -> ClientRequest:
        """Create a new request with a validated status transition.

        Args:
            target: The desired target status.
            **overrides: Additional field overrides.

        Returns:
            A new ClientRequest with the target status.

        Raises:
            ValueError: If the transition is not valid or overrides
                contain ``status``.
        """
        if "status" in overrides:
            msg = "status override is not allowed; pass transition target explicitly"
            raise ValueError(msg)
        validate_request_transition(self.status, target)
        payload = self.model_dump()
        payload.update(overrides)
        payload["status"] = target
        return ClientRequest.model_validate(payload)


class PoolConstraints(BaseModel):
    """Constraints for selecting clients from a pool.

    Attributes:
        min_strictness: Minimum strictness level for selected clients.
        max_strictness: Maximum strictness level for selected clients.
        required_domains: Domains the client must have expertise in.
        max_clients: Maximum number of clients to select.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    min_strictness: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Minimum strictness level",
    )
    max_strictness: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Maximum strictness level",
    )
    required_domains: tuple[NotBlankStr, ...] = Field(
        default=(),
        description="Required expertise domains",
    )
    max_clients: int = Field(
        default=10,
        gt=0,
        description="Maximum number of clients to select",
    )

    @model_validator(mode="after")
    def _validate_strictness_range(self) -> Self:
        """Ensure min_strictness <= max_strictness."""
        if self.min_strictness > self.max_strictness:
            msg = (
                f"min_strictness ({self.min_strictness}) must be <= "
                f"max_strictness ({self.max_strictness})"
            )
            raise ValueError(msg)
        return self


class SimulationConfig(BaseModel):
    """Configuration for a single simulation run.

    Attributes:
        simulation_id: Unique simulation identifier.
        project_id: Project to simulate against.
        rounds: Number of simulation rounds.
        clients_per_round: Clients participating per round.
        requirements_per_client: Requirements each client generates.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    simulation_id: NotBlankStr = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique simulation identifier",
    )
    project_id: NotBlankStr = Field(
        description="Project to simulate against",
    )
    rounds: int = Field(
        default=1,
        gt=0,
        description="Number of simulation rounds",
    )
    clients_per_round: int = Field(
        default=5,
        gt=0,
        description="Clients participating per round",
    )
    requirements_per_client: int = Field(
        default=1,
        gt=0,
        description="Requirements each client generates per round",
    )


class SimulationMetrics(BaseModel):
    """Aggregated metrics from a simulation run.

    Attributes:
        total_requirements: Total requirements generated.
        total_tasks_created: Tasks created from requirements.
        tasks_accepted: Tasks accepted by clients.
        tasks_rejected: Tasks rejected by clients.
        tasks_reworked: Tasks sent back for rework.
        avg_review_rounds: Average review rounds per task.
        round_metrics: Per-round metric snapshots.
        acceptance_rate: Proportion of accepted tasks (computed).
        rework_rate: Proportion of reworked tasks (computed).
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    total_requirements: int = Field(default=0, ge=0)
    total_tasks_created: int = Field(default=0, ge=0)
    tasks_accepted: int = Field(default=0, ge=0)
    tasks_rejected: int = Field(default=0, ge=0)
    tasks_reworked: int = Field(default=0, ge=0)
    avg_review_rounds: float = Field(default=0.0, ge=0.0)
    round_metrics: tuple[dict[str, Any], ...] = Field(
        default=(),
        description="Per-round metric snapshots",
    )

    @computed_field(  # type: ignore[prop-decorator]
        description="Proportion of accepted tasks (0.0-1.0)",
    )
    @property
    def acceptance_rate(self) -> float:
        """Proportion of accepted tasks."""
        if self.total_tasks_created == 0:
            return 0.0
        return self.tasks_accepted / self.total_tasks_created

    @computed_field(  # type: ignore[prop-decorator]
        description="Proportion of reworked tasks (0.0-1.0)",
    )
    @property
    def rework_rate(self) -> float:
        """Proportion of reworked tasks."""
        if self.total_tasks_created == 0:
            return 0.0
        return self.tasks_reworked / self.total_tasks_created
