"""Assert the OpenAPI export is healthy and deterministic.

The ``docs/openapi/openapi.json`` artifact is regenerated by CI on every
docs deploy (see ``.github/workflows/pages.yml``) and is not committed.
This check guards against the ``SYNTHORG_DB_PATH``-unset regression that
caused audit #79 to report 107 missing endpoints: if a future change
removes the ``setdefault`` in ``export_openapi.py`` or breaks wiring so
controllers silently skip registration, the export still succeeds but
the schema is partial.  We catch that here by asserting a minimum path
count and a canary set of endpoints that must always be present.

Invoked from the ``openapi-liveness`` CI job (``.github/workflows/ci.yml``)
on every PR that touches Python sources, tests, scripts, or the export
itself.  Safe to run locally before pushing.
"""

import os
import sys

# Match ``export_openapi.py``'s determinism contract so this check
# exercises the same wiring path CI uses for docs deploys.  Force the
# in-memory SQLite backend and strip ``SYNTHORG_DATABASE_URL`` so a
# pre-set Postgres URL cannot flip the schema onto a different wiring
# path.
os.environ["SYNTHORG_DB_PATH"] = ":memory:"
os.environ.pop("SYNTHORG_DATABASE_URL", None)

# Calibrated to the healthy export floor (~237 paths as of audit #79); a
# small delta tolerates legitimate endpoint additions / deprecations
# without letting a partial-export regression slip through.  Raise in
# lockstep when the committed schema grows.
MIN_PATH_COUNT = 230

# Canary endpoints the audit (2026-04-20) identified as missing when
# the determinism fix regresses.  Their presence proves the full
# integrations / OAuth / clients wiring fired.
CANARY_PATHS = frozenset(
    {
        "/api/v1/health",
        "/api/v1/agents",
        "/api/v1/clients",
        "/api/v1/workflows",
        "/api/v1/budget/config",
        "/api/v1/departments",
    }
)


def main() -> int:
    """Run the export in-memory and assert the schema looks healthy."""
    from synthorg.observability import get_logger, safe_error_description

    logger = get_logger(__name__)

    try:
        from synthorg.api.app import create_app
        from synthorg.api.openapi import inject_rfc9457_responses

        app = create_app()
        schema = inject_rfc9457_responses(app.openapi_schema.to_schema())
    except Exception as exc:
        # TRY400: logger.exception() attaches a traceback whose serialized
        # frame-locals can leak secrets per CLAUDE.md SEC-1.  Use
        # logger.error with safe_error_description instead.
        logger.error(  # noqa: TRY400
            "openapi_export_failed",
            error_type=type(exc).__name__,
            error=safe_error_description(exc),
        )
        return 1

    paths = schema.get("paths") or {}
    path_count = len(paths)

    errors: list[str] = []
    if path_count < MIN_PATH_COUNT:
        errors.append(
            f"Schema has {path_count} paths; expected at least {MIN_PATH_COUNT}. "
            "A controller wiring regression likely caused endpoints to skip "
            "registration.  Check `SYNTHORG_DB_PATH` handling in "
            "scripts/export_openapi.py.",
        )

    missing_canary = sorted(CANARY_PATHS - paths.keys())
    if missing_canary:
        errors.append(
            f"Canary endpoints missing from schema: {missing_canary}. "
            "Either the route was removed (update CANARY_PATHS) or wiring "
            "regressed (fix the underlying controller).",
        )

    if errors:
        logger.error(
            "openapi_liveness_failed",
            path_count=path_count,
            error_count=len(errors),
            errors=errors,
        )
        return 1

    logger.info(
        "openapi_liveness_ok",
        path_count=path_count,
        canary_count=len(CANARY_PATHS),
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
