"""Domain models for the agent evolution system.

Defines adaptation proposals, decisions, and evolution events that
flow through the trigger-proposer-guard-adapter pipeline.
"""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, Self
from uuid import UUID, uuid4

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    model_validator,
)

from synthorg.core.types import NotBlankStr  # noqa: TC001


class AdaptationAxis(StrEnum):
    """Axis along which an agent can be adapted."""

    IDENTITY = "identity"
    STRATEGY_SELECTION = "strategy_selection"
    PROMPT_TEMPLATE = "prompt_template"


class AdaptationSource(StrEnum):
    """What triggered the adaptation proposal."""

    FAILURE = "failure"
    SUCCESS = "success"
    INFLECTION = "inflection"
    SCHEDULED = "scheduled"


class AdaptationProposal(BaseModel):
    """A proposed adaptation to an agent's behavior.

    Generated by an ``AdaptationProposer`` and evaluated by
    ``AdaptationGuard``(s) before being applied by an
    ``AdaptationAdapter``.

    Attributes:
        id: Unique proposal identifier.
        agent_id: Target agent for this adaptation.
        axis: Which aspect of the agent to adapt.
        description: Human-readable description of the change.
        changes: Structured change payload (axis-specific).
        confidence: Proposer's confidence in this adaptation (0-1).
        source: What triggered this proposal.
        proposed_at: When the proposal was generated.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    id: UUID = Field(default_factory=uuid4)
    agent_id: NotBlankStr
    axis: AdaptationAxis
    description: NotBlankStr
    changes: dict[str, Any] = Field(default_factory=dict)
    confidence: float = Field(ge=0.0, le=1.0)
    source: AdaptationSource
    proposed_at: AwareDatetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )


class AdaptationDecision(BaseModel):
    """Result of a guard evaluating an adaptation proposal.

    Attributes:
        proposal_id: Which proposal this decision is for.
        approved: Whether the guard approved the proposal.
        guard_name: Name of the guard that made this decision.
        reason: Human-readable explanation.
        decided_at: When the decision was made.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    proposal_id: UUID
    approved: bool
    guard_name: NotBlankStr
    reason: NotBlankStr
    decided_at: AwareDatetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )


class EvolutionEvent(BaseModel):
    """Record of a completed evolution cycle for one proposal.

    Attributes:
        id: Unique event identifier.
        agent_id: Agent that was (or was not) evolved.
        proposal: The adaptation proposal.
        decision: Final guard decision.
        applied: Whether the adaptation was actually applied.
        identity_version_before: Identity version before adaptation.
        identity_version_after: Identity version after adaptation.
        event_at: When the event was recorded.
    """

    model_config = ConfigDict(frozen=True, allow_inf_nan=False)

    id: UUID = Field(default_factory=uuid4)
    agent_id: NotBlankStr
    proposal: AdaptationProposal
    decision: AdaptationDecision
    applied: bool
    identity_version_before: int | None = None
    identity_version_after: int | None = None
    event_at: AwareDatetime = Field(
        default_factory=lambda: datetime.now(UTC),
    )

    @model_validator(mode="after")
    def _validate_version_consistency(self) -> Self:
        """Ensure version fields are consistent with applied status."""
        if self.applied and self.proposal.axis == AdaptationAxis.IDENTITY:
            if self.identity_version_before is None:
                msg = (
                    "identity_version_before is required "
                    "when an identity adaptation is applied"
                )
                raise ValueError(msg)
            if self.identity_version_after is None:
                msg = (
                    "identity_version_after is required "
                    "when an identity adaptation is applied"
                )
                raise ValueError(msg)
        return self
