"""Execution event constants."""

from typing import Final

EXECUTION_TASK_CREATED: Final[str] = "execution.task.created"
EXECUTION_TASK_TRANSITION: Final[str] = "execution.task.transition"
EXECUTION_COST_RECORDED: Final[str] = "execution.cost.recorded"
EXECUTION_CONTEXT_CREATED: Final[str] = "execution.context.created"
EXECUTION_CONTEXT_TURN: Final[str] = "execution.context.turn"
EXECUTION_CONTEXT_SNAPSHOT: Final[str] = "execution.context.snapshot"
EXECUTION_CONTEXT_NO_TASK: Final[str] = "execution.context.no_task"
EXECUTION_MAX_TURNS_EXCEEDED: Final[str] = "execution.max_turns.exceeded"
EXECUTION_TASK_TRANSITION_FAILED: Final[str] = "execution.task.transition_failed"
EXECUTION_CONTEXT_TRANSITION_FAILED: Final[str] = "execution.context.transition_failed"
EXECUTION_COST_ON_TERMINAL: Final[str] = "execution.cost.on_terminal"

EXECUTION_LOOP_START: Final[str] = "execution.loop.start"
EXECUTION_LOOP_TURN_START: Final[str] = "execution.loop.turn_start"
EXECUTION_LOOP_TURN_COMPLETE: Final[str] = "execution.loop.turn_complete"
EXECUTION_LOOP_TOOL_CALLS: Final[str] = "execution.loop.tool_calls"
EXECUTION_LOOP_TERMINATED: Final[str] = "execution.loop.terminated"
EXECUTION_LOOP_BUDGET_EXHAUSTED: Final[str] = "execution.loop.budget_exhausted"
EXECUTION_LOOP_ERROR: Final[str] = "execution.loop.error"

EXECUTION_ENGINE_CREATED: Final[str] = "execution.engine.created"
EXECUTION_ENGINE_START: Final[str] = "execution.engine.start"
EXECUTION_ENGINE_PROMPT_BUILT: Final[str] = "execution.engine.prompt_built"
EXECUTION_ENGINE_COMPLETE: Final[str] = "execution.engine.complete"
EXECUTION_ENGINE_ERROR: Final[str] = "execution.engine.error"
EXECUTION_ENGINE_INVALID_INPUT: Final[str] = "execution.engine.invalid_input"
EXECUTION_ENGINE_TASK_TRANSITION: Final[str] = "execution.engine.task_transition"
EXECUTION_ENGINE_COST_RECORDED: Final[str] = "execution.engine.cost_recorded"
EXECUTION_ENGINE_COST_SKIPPED: Final[str] = "execution.engine.cost_skipped"
EXECUTION_ENGINE_COST_FAILED: Final[str] = "execution.engine.cost_failed"
EXECUTION_ENGINE_TASK_METRICS: Final[str] = "execution.engine.task_metrics"
EXECUTION_ENGINE_TIMEOUT: Final[str] = "execution.engine.timeout"

EXECUTION_SHUTDOWN_SIGNAL: Final[str] = "execution.shutdown.signal"
EXECUTION_SHUTDOWN_MANAGER_CREATED: Final[str] = "execution.shutdown.manager_created"
EXECUTION_SHUTDOWN_TASK_TRACKED: Final[str] = "execution.shutdown.task_tracked"
EXECUTION_SHUTDOWN_TASK_ERROR: Final[str] = "execution.shutdown.task_error"
EXECUTION_SHUTDOWN_GRACE_START: Final[str] = "execution.shutdown.grace_start"
EXECUTION_SHUTDOWN_FORCE_CANCEL: Final[str] = "execution.shutdown.force_cancel"
EXECUTION_SHUTDOWN_CLEANUP: Final[str] = "execution.shutdown.cleanup"
EXECUTION_SHUTDOWN_CLEANUP_FAILED: Final[str] = "execution.shutdown.cleanup.failed"
EXECUTION_SHUTDOWN_CLEANUP_TIMEOUT: Final[str] = "execution.shutdown.cleanup.timeout"
EXECUTION_SHUTDOWN_COMPLETE: Final[str] = "execution.shutdown.complete"
EXECUTION_LOOP_SHUTDOWN: Final[str] = "execution.loop.shutdown"

EXECUTION_RECOVERY_START: Final[str] = "execution.recovery.start"
EXECUTION_RECOVERY_COMPLETE: Final[str] = "execution.recovery.complete"
EXECUTION_RECOVERY_FAILED: Final[str] = "execution.recovery.failed"
EXECUTION_RECOVERY_SNAPSHOT: Final[str] = "execution.recovery.snapshot"
